### ISSUE TITLE
Error in Siddhi tooling 5.1.2 in Docker when application stopped and started again

### ISSUE THREAD

**Issue by xtrmstep** [wso2-extensions/siddhi-io-kafka#127]
Hi,

Very often I'm getting the following error while stopping and running again my Siddhi application in the tooling. Topic name doesn't matter. The error is disappearing after several stop/start cycles or hard restarting of the container with Siddhi tooling (and applications).

[2020-06-17_22-00-15_334] ERROR {io.siddhi.extension.io.kafka.source.ConsumerKafkaGroup} - Error while creating KafkaConsumerThread for topic(s): [topic_name] 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6c32a9a7 rejected from java.util.concurrent.ThreadPoolExecutor@69ebffb0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at io.siddhi.extension.io.kafka.source.ConsumerKafkaGroup.run(ConsumerKafkaGroup.java:111)
	at io.siddhi.extension.io.kafka.source.KafkaSource.connect(KafkaSource.java:278)
	at io.siddhi.extension.io.kafka.source.KafkaSource.connect(KafkaSource.java:56)
	at io.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:160)
	at io.siddhi.core.SiddhiAppRuntimeImpl.startSources(SiddhiAppRuntimeImpl.java:502)
	at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:427)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.start(DebugRuntime.java:93)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:42)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:761)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by ngocdangrby** [comment]
i have same problem there.
